In [111]:
import numpy as np
import pandas as pd

Step 1: Read all the data files

In [112]:
co_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_co.xlsx')
pb_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_pb.xlsx')
no2_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_no2.xlsx')
o3_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_o3.xlsx')
pm10_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_pm10.xlsx')
pm25_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_pm25.xlsx')
so2_data = pd.read_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Raw Data/monitoring_quick_view_so2.xlsx')

In [113]:
co_data.head()

,Site #,Site Name,County,City,Latitude,Longitude,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024*
0,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,5.3,4.5,2.3,3.5,3.4,3.900,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
1,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,6.2,3.6,5.7,3.8,3.3,3.000,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
2,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,1.5,2.0,1.7,2.2,1.6,1.933,2.296,1.986,1.653,2.032,1.741
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,1.3,1.7,1.8,2.1,1.4,2.000,2.600,2.200,1.500,1.500,2
4,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,5.4,2.1,1.4,1.5,1.5,1.400,1.500,1.200,1.300,1.300,1.3

In [114]:
pb_data.head()

,Site #,Site Name,County,City,Latitude,Longitude,11/20-01/21,12/20-02/21,01/21-03/21,02/21-04/21,...,01/20-03/20,02/20-04/20,03/20-05/20,04/20-06/20,05/20-07/20,06/20-08/20,07/20-09/20,08/20-10/20,9/20-11/20,10/20-12/20
0,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.020,0.010,0.020,0.020,...,0.02,0.03,0.020,0.050,0.050,0.050,0.030,0.030,0.030,0.020
1,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.010,0.010,0.010,0.010,...,0.02,0.02,0.020,0.010,0.010,0.010,0.010,0.010,0.010,0.010
2,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,0.005,0.006,0.006,...,0.01,0.01,0.004,0.005,0.006,0.006,0.006,0.007,0.006,0.006
3,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.040,0.030,0.030,0.030,...,0.02,0.04,0.040,0.030,0.040,0.050,0.030,0.030,0.020,0.030
4,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.010,0.010,0.010,0.010,...,0.01,0.01,0.010,0.010,0.010,0.010,0.010,0.010,0.010,0.010

In [115]:
no2_data.head()

,Site ID,Site Name,County,City,Latitude,Longitude,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024*
0,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,21.9,20.1,18.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2016
1,180890022,Gary IITRI Bunker,Lake,Gary,41.606667,-87.304722,55.0,45.5,42.1,43.8,46.5,45.0,37.3,43.6,46.6,44.3,41.2
2,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,NaN,NaN,NaN,Site began 06/01/2018,44.0,36.7,38.6,36.2,34.6,34.0,36.1
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,58.0,44.4,42.2,38.9,41.4,40.7,37.5,40.4,43.2,44.0,38
4,181410015,South Bend - Shields Dr.,St. Joseph,South Bend,41.696692,-86.214683,45.9,38.0,33.9,36.3,39.3,40.0,32.0,37.0,33.0,30.0,30.3

In [116]:
o3_data.head()

,Site #,Site Name,County,City,Latitude,Longitude,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024**
0,180030002,Leo HS,Allen,Leo,41.221667,-85.017222,0.062,0.063,0.062,0.066,0.064,0.072,0.063,0.065,0.065,0.069,0.075,0.066
1,180030004,Ft Wayne - Beacon St.,Allen,Fort Wayne,41.094722,-85.101944,0.062,0.063,0.059,0.069,0.062,0.069,0.063,0.063,0.059,NaN,NaN,Site discontinued 09/30/2021
2,180030015,Ft Wayne - Coliseum Blvd,Allen,Fort Wayne,41.081864,-85.088313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 10/13/2023,0.061
3,180050007,Hope,Bartholomew,Hope,39.294322,-85.766816,0.066,0.067,0.066,0.071,0.064,0.069,0.062,0.065,0.063,0.066,0.076,0.066
4,180110001,Whitestown,Boone,NaN,39.997484,-86.395172,0.068,0.066,0.064,0.070,0.066,0.073,0.066,0.069,0.065,0.068,0.076,0.065

In [117]:
pm10_data.head()

,Site #,Site Name,County,City,Latitude,Longitude,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,180030004.0,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094742,-85.101876,38,39,45,59,38.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/08/2007
1,180190005.0,Jeffersonville - Spring St,Clark,Jeffersonville,38.270833,-85.740278,43,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/26/2003
2,180190006.0,Jeffersonville - Walnut St,Clark,Jeffersonville,38.277675,-85.740153,Site began 06/23/2003,53,47,63,59.0,53.0,51,51,57.0,50.0,59.0,33.0,40
3,180190007.0,Jefferson - Jeffboat,Clark,Jeffersonville,38.278666,-85.724350,Site began 10/01/2003,67,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 07/31/2004
4,180270004.0,Washington,Daviess,Washington,38.639167,-87.222222,55,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/23/2003

In [118]:
pm25_data.head()

,Site #,Site Name,County,City,Latitude,Longitude,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024**
0,180030004,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094722,-85.101944,10.70,10.00,8.60,8.16,9.1,8.95,8.33,8.6,NaN,NaN,Site discontinued 09/30/2021
1,180030015,Fort Wayne - Coliseum,Allen,Fort Wayne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,site began 10/30/2023,8.37,8.5
2,180050008,Columbus - Rocky Ford Drive,Bartholomew,Columbus,39.237457,-85.891332,10.70,9.50,8.20,7,7.5,6.89,6.67,7.8,6.65,8.41,6.9
3,180190006,Jeffersonville - Walnut St.,Clark,Jeffersonville,38.277675,-85.740153,11.93,10.71,9.28,8.68,9.16,8.39,NaN,NaN,NaN,NaN,Site discontinued 05/18/2019
4,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,9.49,8.83,7.85,7.37,7.94,7.20,7.07,8.2,7.3,NaN,Site discontinued 12/31/2022

In [119]:
so2_data.head()

,Site ID,Site Name,County,City,Latitude,Longitude,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024*
0,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 01/11/2023,4.6,5
1,180431004,New Albany-Green Valley Elem. Sch.,Floyd,New Albany,38.308056,-85.834167,32.0,20.5,43.8,25.5,11.2,8.2,9,4.6,4.5,3.8,6.5,NaN,Site discontinued 01/04/2023
2,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,47.0,43.2,53.1,35.4,29.2,36.2,25.6,35.1,31.5,32.2,20.4,23.5,38.4
3,180890034,East Chicago-Marina,Lake,East Chicago,41.653446,-87.435435,NaN,NaN,NaN,NaN,NaN,NaN,Site began 11/01/2019,14.2,22.7,18.5,10,19.3,12.9
4,180892008,Hammond - 141st St.,Lake,Hammond,41.639444,-87.493611,28.1,23.7,20.2,25.9,21,18.4,19.1,20.4,25,19.3,13.7,21.2,17.4

### CO Data Cleaning

In [120]:
co_melted = co_data.melt(id_vars=['Site #', 'Site Name', 'County', 'City', 'Latitude ', 'Longitude'], 
                    var_name='Year', value_name='Value')

In [121]:
co_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2014,5.3
1,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2014,6.2
2,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2014,1.5
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2014,1.3
4,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2014,5.4
5,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2015,4.5
6,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2015,3.6
7,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2015,2.0
8,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2015,1.7
9,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2015,2.1
10,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2016,2.3
11,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2016,5.7
12,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2016,1.7
13,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2016,1.8
14,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2016,1.4
15,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2017,3.5
16,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2017,3.8
17,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2017,2.2
18,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2017,2.1
19,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2017,1.5
20,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2018,3.4
21,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2018,3.3
22,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2018,1.6
23,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2018,1.4
24,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2018,1.5
25,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2019,3.9
26,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2019,3.0
27,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2019,1.933
28,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2019,2.0
29,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2019,1.4
30,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2020,NaN
31,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2020,NaN
32,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2020,2.296
33,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2020,2.6
34,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2020,1.5
35,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2021,NaN
36,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2021,NaN
37,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2021,1.986
38,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2021,2.2
39,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2021,1.2
40,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2022,NaN
41,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2022,NaN
42,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2022,1.653
43,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2022,1.5
44,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2022,1.3
45,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2023,NaN
46,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2023,NaN
47,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2023,2.032
48,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2023,1.5
49,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2023,1.3
50,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2024*,Site discontinued 12/31/2019
51,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2024*,Site discontinued 12/31/2019
52,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2024*,1.741
53,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2024*,2
54,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2024*,1.3

In [122]:
co_melted.isnull().sum()

Site #       0
Site Name    0
County       0
City         0
Latitude     0
Longitude    0
Year         0
Value        8
dtype: int64

In [123]:
co_melted['Value'] = co_melted['Value'].replace('Site discontinued 12/31/2019', np.nan)

In [124]:
co_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2014,5.3
1,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2014,6.2
2,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2014,1.5
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2014,1.3
4,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2014,5.4
5,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2015,4.5
6,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2015,3.6
7,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2015,2.0
8,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2015,1.7
9,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2015,2.1
10,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2016,2.3
11,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2016,5.7
12,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2016,1.7
13,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2016,1.8
14,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2016,1.4
15,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2017,3.5
16,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2017,3.8
17,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2017,2.2
18,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2017,2.1
19,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2017,1.5
20,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2018,3.4
21,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2018,3.3
22,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2018,1.6
23,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2018,1.4
24,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2018,1.5
25,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2019,3.9
26,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2019,3.0
27,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2019,1.933
28,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2019,2.0
29,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2019,1.4
30,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2020,NaN
31,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2020,NaN
32,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2020,2.296
33,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2020,2.6
34,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2020,1.5
35,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2021,NaN
36,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2021,NaN
37,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2021,1.986
38,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2021,2.2
39,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2021,1.2
40,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2022,NaN
41,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2022,NaN
42,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2022,1.653
43,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2022,1.5
44,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2022,1.3
45,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2023,NaN
46,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2023,NaN
47,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2023,2.032
48,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2023,1.5
49,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2023,1.3
50,180890015,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2024*,Site discontinued 12/31/2019
51,180970072,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2024*,Site discontinued 12/31/2019
52,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2024*,1.741
53,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2024*,2
54,181630022,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2024*,1.3

### Pb Data Cleaning

In [125]:
pb_data.head()

,Site #,Site Name,County,City,Latitude,Longitude,11/20-01/21,12/20-02/21,01/21-03/21,02/21-04/21,...,01/20-03/20,02/20-04/20,03/20-05/20,04/20-06/20,05/20-07/20,06/20-08/20,07/20-09/20,08/20-10/20,9/20-11/20,10/20-12/20
0,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.020,0.010,0.020,0.020,...,0.02,0.03,0.020,0.050,0.050,0.050,0.030,0.030,0.030,0.020
1,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.010,0.010,0.010,0.010,...,0.02,0.02,0.020,0.010,0.010,0.010,0.010,0.010,0.010,0.010
2,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,0.005,0.006,0.006,...,0.01,0.01,0.004,0.005,0.006,0.006,0.006,0.007,0.006,0.006
3,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.040,0.030,0.030,0.030,...,0.02,0.04,0.040,0.030,0.040,0.050,0.030,0.030,0.020,0.030
4,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.010,0.010,0.010,0.010,...,0.01,0.01,0.010,0.010,0.010,0.010,0.010,0.010,0.010,0.010

Melt the dataframe to convert the time period as a 'Year' column

In [126]:
pb_melted = pb_data.melt(id_vars=['Site #', 'Site Name', 'County', 'City', 'Latitude', 'Longitude'], 
                    var_name='Period', value_name='Value')

Extract the year from the 'Period' column and append '20' at the beginning to get the standard year format.

In [127]:
pb_melted['Year'] = pb_melted['Period'].apply(lambda x: '20' + x.split('-')[1].split('/')[1])

Drop the 'Period' column as it becomes redundant as is of no use now.

In [128]:
pb_melted = pb_melted.drop(columns=['Period'])

In [129]:
pb_melted.tail(40)

,Site #,Site Name,County,City,Latitude,Longitude,Value,Year
380,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.02,2020
381,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.02,2020
382,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.004,2020
383,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.04,2020
384,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
385,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.05,2020
386,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
387,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.005,2020
388,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.03,2020
389,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
390,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.05,2020
391,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
392,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2020
393,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.04,2020
394,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
395,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.05,2020
396,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
397,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2020
398,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.05,2020
399,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
400,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.03,2020
401,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
402,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2020
403,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.03,2020
404,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
405,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.03,2020
406,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
407,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.007,2020
408,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.03,2020
409,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
410,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.03,2020
411,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
412,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2020
413,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.02,2020
414,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
415,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.02,2020
416,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.01,2020
417,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2020
418,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.03,2020
419,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020

Check for null values in the data

In [130]:
pb_melted.isnull().sum()

Site #        0
Site Name     0
County        0
City         84
Latitude      0
Longitude     0
Value        28
Year          0
dtype: int64

In [131]:
pb_melted[pb_melted.isnull().any(axis=1)]

,Site #,Site Name,County,City,Latitude,Longitude,Value,Year
4,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2021
9,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2021
14,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2021
19,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2021
24,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2021
...,...,...,...,...,...,...,...,...
399,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
404,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
409,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
414,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020
419,181270027,Burns Harbor - Port of Indiana,Porter,NaN,41.635181,-87.150367,0.01,2020

In [132]:
pb_melted.loc[pb_melted['Site Name'] == 'Burns Harbor - Port of Indiana', 'City'] = 'Burns Harbor - Port of Indiana'

In [133]:
pb_melted.isnull().sum()

Site #        0
Site Name     0
County        0
City          0
Latitude      0
Longitude     0
Value        28
Year          0
dtype: int64

In [134]:
pb_unique_values = pb_melted['Value'].unique()
print(pb_unique_values)

[0.02 0.01 0.006 0.04 0.005 0.03 0.008 0.009 0.007 0.15 0.16 0.011 0.012
 0.0 0.004 0.05 0.06 0.1 0.08 0.003 nan 'Site began 08/03/2018' 0.31 0.22
 0.18 0.19 0.12 0.07 0.09]

In [135]:
pb_melted['Value'] = pb_melted['Value'].replace('Site began 08/03/2018', np.nan)

In [136]:
pb_melted.isnull().sum()

Site #        0
Site Name     0
County        0
City          0
Latitude      0
Longitude     0
Value        29
Year          0
dtype: int64

In [137]:
pb_melted

,Site #,Site Name,County,City,Latitude,Longitude,Value,Year
0,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.020,2021
1,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.010,2021
2,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2021
3,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.040,2021
4,181270027,Burns Harbor - Port of Indiana,Porter,Burns Harbor - Port of Indiana,41.635181,-87.150367,0.010,2021
...,...,...,...,...,...,...,...,...
415,180350009,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,40.158417,-85.415021,0.020,2020
416,180890032,Gary - 4th Ave,Lake,Gary,41.603582,-87.332658,0.010,2020
417,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,0.006,2020
418,180890037,Hammond - E. Lakeview St,Lake,Hammond,41.674278,-87.494981,0.030,2020
419,181270027,Burns Harbor - Port of Indiana,Porter,Burns Harbor - Port of Indiana,41.635181,-87.150367,0.010,2020

### NO2 Data Cleaning

In [138]:
no2_data

,Site ID,Site Name,County,City,Latitude,Longitude,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024*
0,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,21.9,20.1,18.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2016
1,180890022,Gary IITRI Bunker,Lake,Gary,41.606667,-87.304722,55.0,45.5,42.1,43.8,46.5,45.0,37.3,43.6,46.6,44.3,41.2
2,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,NaN,NaN,NaN,Site began 06/01/2018,44.0,36.7,38.6,36.2,34.6,34.0,36.1
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,58.0,44.4,42.2,38.9,41.4,40.7,37.5,40.4,43.2,44.0,38
4,181410015,South Bend - Shields Dr.,St. Joseph,South Bend,41.696692,-86.214683,45.9,38.0,33.9,36.3,39.3,40.0,32.0,37.0,33.0,30.0,30.3
5,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,36.2,35.2,32.2,28.5,30.9,32.0,30.4,30.4,30.1,25.0,27.4
6,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,23.9,25.4,20.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2016

In [139]:
no2_melted = no2_data.melt(id_vars=['Site ID', 'Site Name', 'County', 'City', 'Latitude', 'Longitude'], 
                    var_name='Year', value_name='Value')

In [140]:
no2_melted

,Site ID,Site Name,County,City,Latitude,Longitude,Year,Value
0,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2014,21.9
1,180890022,Gary IITRI Bunker,Lake,Gary,41.606667,-87.304722,2014,55.0
2,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2014,NaN
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2014,58.0
4,181410015,South Bend - Shields Dr.,St. Joseph,South Bend,41.696692,-86.214683,2014,45.9
...,...,...,...,...,...,...,...,...
72,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2024*,36.1
73,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2024*,38
74,181410015,South Bend - Shields Dr.,St. Joseph,South Bend,41.696692,-86.214683,2024*,30.3
75,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,2024*,27.4
76,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2024*,Site discontinued 12/31/2016

In [141]:
no2_melted.isnull().sum()

Site ID       0
Site Name     0
County        0
City         11
Latitude      0
Longitude     0
Year          0
Value        17
dtype: int64

In [142]:
no2_melted[no2_melted.isnull().any(axis=1)]

,Site ID,Site Name,County,City,Latitude,Longitude,Year,Value
2,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2014,NaN
6,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2014,23.9
9,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2015,NaN
13,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2015,25.4
16,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2016,NaN
20,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2016,20.4
21,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2017,NaN
27,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2017,NaN
28,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2018,NaN
34,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2018,NaN
35,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2019,NaN
41,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2019,NaN
42,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2020,NaN
48,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2020,NaN
49,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2021,NaN
55,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2021,NaN
56,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2022,NaN
62,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2022,NaN
63,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2023,NaN
69,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2023,NaN
76,181830003,Larwill,Whitley,NaN,41.169646,-85.629292,2024*,Site discontinued 12/31/2016

In [143]:
no2_melted.loc[no2_melted['Site Name'] == 'Larwill', 'City'] = 'Richland'

In [144]:
no2_melted

,Site ID,Site Name,County,City,Latitude,Longitude,Year,Value
0,180050007,Columbus,Bartholomew,Hope,39.294322,-85.766816,2014,21.9
1,180890022,Gary IITRI Bunker,Lake,Gary,41.606667,-87.304722,2014,55.0
2,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2014,NaN
3,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2014,58.0
4,181410015,South Bend - Shields Dr.,St. Joseph,South Bend,41.696692,-86.214683,2014,45.9
...,...,...,...,...,...,...,...,...
72,180970078,Washington Park,Marion,Indianapolis,39.811097,-86.114469,2024*,36.1
73,180970087,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2024*,38
74,181410015,South Bend - Shields Dr.,St. Joseph,South Bend,41.696692,-86.214683,2024*,30.3
75,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,2024*,27.4
76,181830003,Larwill,Whitley,Richland,41.169646,-85.629292,2024*,Site discontinued 12/31/2016

In [145]:
no2_melted.isnull().sum()

Site ID       0
Site Name     0
County        0
City          0
Latitude      0
Longitude     0
Year          0
Value        17
dtype: int64

In [146]:
no2_unique_values = no2_melted['Value'].unique()
print(no2_unique_values)

[21.9 55.0 nan 58.0 45.9 36.2 23.9 20.1 45.5 44.4 38.0 35.2 25.4 18.5 42.1
 42.2 33.9 32.2 20.4 43.8 'Site began 06/01/2018' 38.9 36.3 28.5 46.5 44.0
 41.4 39.3 30.9 45.0 36.7 40.7 40.0 32.0 37.3 38.6 37.5 30.4 43.6 40.4
 37.0 46.6 34.6 43.2 33.0 30.1 44.3 34.0 30.0 25.0
 'Site discontinued 12/31/2016' 41.2 36.1 30.3 27.4]

In [147]:
no2_melted['Value'] = no2_melted['Value'].replace('Site began 06/01/2018', np.nan)
no2_melted['Value'] = no2_melted['Value'].replace('Site discontinued 12/31/2016', np.nan)

In [148]:
no2_melted.isnull().sum()

Site ID       0
Site Name     0
County        0
City          0
Latitude      0
Longitude     0
Year          0
Value        20
dtype: int64

In [149]:
no2_melted.columns

Index(['Site ID', 'Site Name', 'County', 'City', 'Latitude', 'Longitude',
       'Year', 'Value'],
      dtype='object')

In [150]:
no2_melted.rename(columns={'Site ID': 'Site #'}, inplace = True)

In [151]:
no2_melted.columns

Index(['Site #', 'Site Name', 'County', 'City', 'Latitude', 'Longitude',
       'Year', 'Value'],
      dtype='object')

### O3 Data Cleaning

In [152]:
o3_data

,Site #,Site Name,County,City,Latitude,Longitude,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024**
0,180030002,Leo HS,Allen,Leo,41.221667,-85.017222,0.062,0.063,0.062,0.066,0.064,0.072,0.063,0.065,0.065,0.069,0.075,0.066
1,180030004,Ft Wayne - Beacon St.,Allen,Fort Wayne,41.094722,-85.101944,0.062,0.063,0.059,0.069,0.062,0.069,0.063,0.063,0.059,NaN,NaN,Site discontinued 09/30/2021
2,180030015,Ft Wayne - Coliseum Blvd,Allen,Fort Wayne,41.081864,-85.088313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 10/13/2023,0.061
3,180050007,Hope,Bartholomew,Hope,39.294322,-85.766816,0.066,0.067,0.066,0.071,0.064,0.069,0.062,0.065,0.063,0.066,0.076,0.066
4,180110001,Whitestown,Boone,NaN,39.997484,-86.395172,0.068,0.066,0.064,0.070,0.066,0.073,0.066,0.069,0.065,0.068,0.076,0.065
5,180130001,Helmsburg,Brown,Helmsburg,39.263914,-86.292269,Site began 05/14/2014,0.058,0.062,0.063,0.062,0.065,0.059,0.062,0.062,0.060,0.066,0.06
6,180150002,Flora,Carroll,NaN,40.540556,-86.553056,0.065,0.064,0.064,0.066,0.061,0.066,0.061,0.062,0.066,0.066,0.074,0.064
7,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,0.067,0.066,0.074,0.072,0.068,0.071,0.064,0.062,0.063,0.064,0.072,0.073
8,180350010,Albany,Delaware,Albany,40.300000,-85.245556,0.061,0.054,0.058,0.067,0.063,0.070,0.059,0.062,0.064,0.068,0.071,0.065
9,180390007,Bristol,Elkhart,Bristol,41.718050,-85.830550,0.055,0.055,0.058,0.072,0.064,0.070,0.058,0.062,0.063,0.060,0.071,0.065
10,180431004,New Albany,Floyd,New Albany,38.308056,-85.834167,0.068,0.068,0.067,0.073,0.074,0.073,0.063,0.066,0.064,0.063,NaN,Site discontinued 01/04/2023
11,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.064,0.063,0.071,0.065
12,180550001,Plummer,Greene,NaN,38.985578,-86.990120,0.068,0.064,0.067,0.069,0.067,0.066,0.062,0.064,0.066,0.063,0.077,0.064
13,180570006,Noblesville - 191st St.,Hamilton,Noblesville,40.068297,-85.992451,0.063,0.058,0.063,0.069,0.069,0.071,0.064,0.063,0.065,0.065,0.072,0.067
14,180590003,Fortville - Municipal Building,Hancock,Fortville,39.934870,-85.840671,0.061,0.053,0.062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 09/30/2015
15,180630004,Avon,Hendricks,Avon,39.758967,-86.397148,0.057,0.057,0.055,0.068,0.067,0.067,0.059,0.063,0.061,0.063,0.071,0.061
16,180670004,Kokomo - E. Vaile Ave,Howard,Kokomo,40.481347,-86.109688,NaN,NaN,NaN,NaN,Site began 01/01/2018,0.072,0.063,0.064,0.064,0.071,0.074,0.066
17,180690002,Roanoke Elem School,Huntington,Roanoke,40.960556,-85.380000,0.059,0.056,0.054,0.066,0.061,0.066,0.060,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
18,180710001,Brownstown,Jackson,NaN,38.920798,-86.080523,0.063,0.064,0.064,0.070,0.063,0.065,0.060,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
19,180810002,Indian Creek Elementary School,Johnson,Trafalgar,39.417155,-86.152406,0.062,0.056,0.063,0.062,0.063,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
20,180839991,Vincennes*,Knox,Vincennes,38.740800,-87.485300,0.064,0.062,0.063,0.071,0.066,0.071,0.061,0.065,0.069,0.065,0.075,0.066
21,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,0.064,0.067,0.064,0.070,0.07,0.071,0.065,0.074,0.070,0.071,0.076,0.069
22,180890030,Whiting - Whiting High School,Lake,Whiting,41.681497,-87.493836,0.062,0.065,0.070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
23,180892008,Hammond - 141st St.,Lake,Hammond,41.639444,-87.493611,0.063,0.067,0.060,0.068,0.069,0.062,0.065,0.071,0.068,0.069,0.075,0.067
24,180910005,Michigan City - W. Michigan Blvd,LaPorte,Michigan City,41.716944,-86.907500,0.069,0.070,0.067,0.043,0.077,0.082,0.071,0.079,0.072,0.068,0.077,0.069
25,180910010,LaPorte - E. Lincolnway,LaPorte,LaPorte,41.629167,-86.684722,0.064,0.061,0.061,0.068,0.072,0.071,0.061,0.064,0.064,0.065,0.07,0.064
26,180950010,Emporia,Madison,NaN,40.002500,-85.656944,0.063,0.054,0.054,0.064,0.068,0.072,0.064,0.059,NaN,NaN,NaN,Site discontinued 12/31/2019
27,180950011,Anderson Eastside Elementary,Madison,Anderson,40.125703,-85.652184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 01/01/2021,0.065,0.071,0.073,0.066
28,180970050,Indpls - Ft Harrison,Marion,Indianapolis,39.858961,-86.021341,0.059,0.066,0.069,0.073,0.068,0.076,0.067,0.062,0.066,0.069,0.072,0.064
29,180970057,Indpls - Harding St.,Marion,Indianapolis,39.749019,-86.186314,0.062,0.066,0.061,0.069,0.064,0.075,0.065,0.067,0.067,0.071,0.073,0.064
30,180970073,Indpls - 16th St.,Marion,Indianapolis,39.789486,-86.060850,0.067,0.065,0.062,0.068,0.069,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
31,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,0.069,0.061,0.067,0.070,0.067,0.072,0.066,0.063,0.065,0.072,0.077,0.066
32,180970087,Indpls - I-70 E.,Marion,Indianapolis,39.787933,-86.130880,Site began 05/14/2014,0.061,0.064,0.068,0.063,0.070,0.060,0.059,0.060,0.067,0.071,0.06
33,181090005,Monrovia,Morgan,Monrovia,39.575596,-86.477914,0.065,0.064,0.063,0.065,0.058,0.066,0.064,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
34,181230009,Leopold,Perry,NaN,38.113101,-86.603611,0.064,0.067,0.067,0.069,0.066,0.063,0.063,0.065,0.064,0.065,0.067,0.065
35,181270024,Ogden Dunes,Porter,Ogden Dunes,41.617500,-87.199167,0.069,0.071,0.066,0.070,0.072,0.071,0.068,0.076,0.072,0.073,0.077,0.07
36,181270026,Valparaiso,Porter,Valparaiso,41.510278,-87.038611,0.063,0.067,0.060,0.071,0.077,0.071,0.071,0.067,0.066,0.067,0.072,0.065
37,181290003,St. Phillips,Posey,NaN,38.005278,-87.718333,0.065,0.065,0.067,0.068,0.068,0.067,0.061,0.064,0.059,0.060,0.074,0.063
38,181410010,Potato Creek State Park,St Joseph,NaN,41.551667,-86.370556,0.057,0.059,0.058,0.069,0.068,0.069,0.061,0.067,0.062,0.061,0.07,0.063
39,181410015,South Bend-Shields Dr.,St Joseph,South Bend,41.696692,-86.214683,0.065,0.067,0.066,0.072,0.072,0.073,0.065,0.065,0.066,0.071,0.073,0.069
40,181410016,Granger-Beckley St.,St Joseph,South Bend,41.754870,-86.110090,0.059,0.064,0.064,0.071,0.068,0.070,0.061,0.066,0.066,0.066,0.072,0.066
41,181450001,Fairland,Shelby,NaN,39.613423,-85.870648,0.066,0.062,0.059,0.065,0.069,0.072,0.063,0.061,0.065,0.065,0.071,0.065
42,181630013,Inglefield,Vanderburgh,NaN,38.113889,-87.536944,0.068,0.070,0.068,0.070,0.068,0.066,0.060,0.064,0.064,0.064,0.072,0.066
43,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,0.066,0.068,0.072,0.072,0.064,0.068,0.064,0.067,0.064,0.067,0.075,0.064
44,181670018,Terre Haute - Lafayette Ave.,Vigo,Terre Haute,39.486111,-87.401389,0.061,0.062,0.064,0.069,0.068,0.069,0.063,0.064,0.063,0.068,0.07,0.064
45,181670024,Sandcut,Vigo,NaN,39.560556,-87.313056,0.066,0.056,0.062,0.067,0.066,0.068,0.061,0.062,0.061,0.065,0.072,0.062
46,181699991,Salamonie Reservoir*,Wabash,Lagro,40.816000,-85.661100,0.068,0.066,0.068,0.071,0.065,0.076,0.064,0.067,0.062,0.068,0.07,0.064
47,181730008,Boonville,Warrick,Boonville,38.051944,-87.278333,0.063,0.065,0.069,0.070,0.068,0.070,0.062,0.065,0.066,0.068,0.074,0.067
48,181730009,Lynnville,Warrick,Lynnville,38.194501,-87.341396,0.061,0.064,0.062,0.072,0.064,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 10/31/2017
49,181730011,Dayville,Warrick,NaN,37.954450,-87.321933,0.066,0.066,0.065,0.071,0.068,0.065,0.059,0.066,0.064,0.066,0.072,0.065
50,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,0.061,0.063,0.064,0.066,0.067,0.066,0.060,0.06,0.062,0.062,0.075,0.063
51,260270003,Cassopolis,"Cass, MI",NaN,41.895570,-86.001629,0.071,0.066,0.068,0.077,0.072,0.075,0.063,0.075,0.067,0.068,0.075,0.066

In [153]:
o3_melted = o3_data.melt(id_vars=['Site #', 'Site Name', 'County', 'City', 'Latitude', 'Longitude'], 
                    var_name='Year', value_name='Value')

In [154]:
o3_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030002,Leo HS,Allen,Leo,41.221667,-85.017222,2013,0.062
1,180030004,Ft Wayne - Beacon St.,Allen,Fort Wayne,41.094722,-85.101944,2013,0.062
2,180030015,Ft Wayne - Coliseum Blvd,Allen,Fort Wayne,41.081864,-85.088313,2013,NaN
3,180050007,Hope,Bartholomew,Hope,39.294322,-85.766816,2013,0.066
4,180110001,Whitestown,Boone,NaN,39.997484,-86.395172,2013,0.068
...,...,...,...,...,...,...,...,...
619,181730008,Boonville,Warrick,Boonville,38.051944,-87.278333,2024**,0.067
620,181730009,Lynnville,Warrick,Lynnville,38.194501,-87.341396,2024**,Site discontinued 10/31/2017
621,181730011,Dayville,Warrick,NaN,37.954450,-87.321933,2024**,0.065
622,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2024**,0.063
623,260270003,Cassopolis,"Cass, MI",NaN,41.895570,-86.001629,2024**,0.066

In [155]:
o3_melted.isnull().sum()

Site #         0
Site Name      0
County         0
City         180
Latitude       0
Longitude      0
Year           0
Value         81
dtype: int64

In [156]:
o3_melted[o3_melted.isnull().any(axis=1)]

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
2,180030015,Ft Wayne - Coliseum Blvd,Allen,Fort Wayne,41.081864,-85.088313,2013,NaN
4,180110001,Whitestown,Boone,NaN,39.997484,-86.395172,2013,0.068
6,180150002,Flora,Carroll,NaN,40.540556,-86.553056,2013,0.065
7,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2013,0.067
11,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,2013,NaN
...,...,...,...,...,...,...,...,...
614,181630013,Inglefield,Vanderburgh,NaN,38.113889,-87.536944,2024**,0.066
617,181670024,Sandcut,Vigo,NaN,39.560556,-87.313056,2024**,0.062
621,181730011,Dayville,Warrick,NaN,37.954450,-87.321933,2024**,0.065
622,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2024**,0.063
623,260270003,Cassopolis,"Cass, MI",NaN,41.895570,-86.001629,2024**,0.066

In [157]:
o3_melted[o3_melted['City'].isnull()]['Site Name'].drop_duplicates()

4                  Whitestown
6                       Flora
7      Charlestown State Park
12                    Plummer
18                 Brownstown
26                    Emporia
34                    Leopold
37               St. Phillips
38    Potato Creek State Park
41                   Fairland
42                 Inglefield
45                    Sandcut
49                   Dayville
50                West Union
51                 Cassopolis
Name: Site Name, dtype: object

In [158]:
site_to_city = {
    'Whitestown': 'Whitestown',
    'Flora': 'Flora',
    'Charlestown State Park': 'Charlestown',
    'Plummer': 'Plummer',
    'Brownstown': 'Brownstown',
    'Emporia': 'Emporia',
    'Leopold': 'Leopold',
    'St. Phillips': 'St. Phillips',
    'Potato Creek State Park': 'North Liberty',
    'Fairland': 'Fairland',
    'Inglefield': 'Inglefield',
    'Sandcut': 'Sandcut',
    'Dayville': 'Dayville',
    'West Union': 'West Union',
    'Cassopolis': 'Cassopolis'
}

In [159]:
o3_melted['City'] = o3_melted.apply(
    lambda row: site_to_city.get(row['Site Name'], row['City']) if pd.isnull(row['City']) else row['City'], axis=1)

In [160]:
o3_melted[o3_melted['City'].isnull()]

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
50,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2013,0.061
102,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2014,0.063
154,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2015,0.064
206,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2016,0.066
258,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2017,0.067
310,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2018,0.066
362,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2019,0.06
414,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2020,0.06
466,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2021,0.062
518,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2022,0.062
570,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2023,0.075
622,170230001,West Union,"Clark, IL",NaN,39.210857,-87.668297,2024**,0.063

In [161]:
o3_melted['County'] = o3_melted['County'].replace({'Clark, IL': 'Clark', 'Cass, MI': 'Cass'})

In [162]:
o3_melted[o3_melted['City'].isnull()]

        Site #    Site Name County City   Latitude  Longitude    Year  Value
50   170230001  West Union   Clark  NaN  39.210857 -87.668297    2013  0.061
102  170230001  West Union   Clark  NaN  39.210857 -87.668297    2014  0.063
154  170230001  West Union   Clark  NaN  39.210857 -87.668297    2015  0.064
206  170230001  West Union   Clark  NaN  39.210857 -87.668297    2016  0.066
258  170230001  West Union   Clark  NaN  39.210857 -87.668297    2017  0.067
310  170230001  West Union   Clark  NaN  39.210857 -87.668297    2018  0.066
362  170230001  West Union   Clark  NaN  39.210857 -87.668297    2019   0.06
414  170230001  West Union   Clark  NaN  39.210857 -87.668297    2020   0.06
466  170230001  West Union   Clark  NaN  39.210857 -87.668297    2021  0.062
518  170230001  West Union   Clark  NaN  39.210857 -87.668297    2022  0.062
570  170230001  West Union   Clark  NaN  39.210857 -87.668297    2023  0.075
622  170230001  West Union   Clark  NaN  39.210857 -87.668297  2024**  0.063

In [163]:
o3_melted[o3_melted['County'].notnull()]['County'].unique()

array(['Allen ', 'Bartholomew', 'Boone', 'Brown', 'Carroll', 'Clark ',
       'Delaware', 'Elkhart', 'Floyd', 'Greene', 'Hamilton ', 'Hancock',
       'Hendricks', 'Howard', 'Huntington', 'Jackson', 'Johnson', 'Knox',
       'Lake', 'LaPorte', 'Madison', 'Marion', 'Morgan', 'Perry',
       'Porter', 'Posey', 'St Joseph', 'Shelby', 'Vanderburgh  ',
       'Vanderburgh', 'Vigo', 'Wabash', 'Warrick ', 'Clark', 'Cass'],
      dtype=object)

In [164]:
o3_melted['Value'].unique()

array([0.062, nan, 0.066, 0.068, 'Site began 05/14/2014', 0.065, 0.067,
       0.061, 0.055, 0.063, 0.057, 0.059, 0.064, 0.069, 0.071, 0.058,
       0.054, 0.053, 0.056, 0.07, 0.074, 0.06, 0.072, 0.073, 0.043, 0.077,
       'Site began 01/01/2018', 0.082, 0.076, 0.075, 0.079,
       'Site began 01/01/2021', 'Site began 10/13/2023',
       'Site discontinued 09/30/2021', 'Site discontinued 01/04/2023',
       'Site discontinued 09/30/2015', 'Site discontinued 12/31/2019',
       'Site discontinued 10/31/2017'], dtype=object)

In [165]:
o3_melted['Value'] = pd.to_numeric(o3_melted['Value'], errors='coerce')

In [166]:
o3_melted['Value'].unique()

array([0.062,   nan, 0.066, 0.068, 0.065, 0.067, 0.061, 0.055, 0.063,
       0.057, 0.059, 0.064, 0.069, 0.071, 0.058, 0.054, 0.053, 0.056,
       0.07 , 0.074, 0.06 , 0.072, 0.073, 0.043, 0.077, 0.082, 0.076,
       0.075, 0.079])

In [167]:
o3_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030002,Leo HS,Allen,Leo,41.221667,-85.017222,2013,0.062
1,180030004,Ft Wayne - Beacon St.,Allen,Fort Wayne,41.094722,-85.101944,2013,0.062
2,180030015,Ft Wayne - Coliseum Blvd,Allen,Fort Wayne,41.081864,-85.088313,2013,NaN
3,180050007,Hope,Bartholomew,Hope,39.294322,-85.766816,2013,0.066
4,180110001,Whitestown,Boone,Whitestown,39.997484,-86.395172,2013,0.068
...,...,...,...,...,...,...,...,...
619,181730008,Boonville,Warrick,Boonville,38.051944,-87.278333,2024**,0.067
620,181730009,Lynnville,Warrick,Lynnville,38.194501,-87.341396,2024**,NaN
621,181730011,Dayville,Warrick,Dayville,37.954450,-87.321933,2024**,0.065
622,170230001,West Union,Clark,NaN,39.210857,-87.668297,2024**,0.063
623,260270003,Cassopolis,Cass,Cassopolis,41.895570,-86.001629,2024**,0.066

### PM10 Data Cleaning

In [168]:
pm10_data

,Site #,Site Name,County,City,Latitude,Longitude,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,180030004.0,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094742,-85.101876,38,39,45,59,38.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/08/2007
1,180190005.0,Jeffersonville - Spring St,Clark,Jeffersonville,38.270833,-85.740278,43,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/26/2003
2,180190006.0,Jeffersonville - Walnut St,Clark,Jeffersonville,38.277675,-85.740153,Site began 06/23/2003,53,47,63,59.0,53.0,51,51,57.0,50.0,59.0,33.0,40
3,180190007.0,Jefferson - Jeffboat,Clark,Jeffersonville,38.278666,-85.724350,Site began 10/01/2003,67,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 07/31/2004
4,180270004.0,Washington,Daviess,Washington,38.639167,-87.222222,55,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/23/2003
5,180330001.0,Auburn,Dekalb,Auburn,41.363610,-85.061660,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 10/31/2002
6,180372001.0,Jasper - Post Office,Dubois,Jasper,38.391389,-86.929167,52,47,47,68,49.0,49.0,36,36,47.0,47.0,31.0,30.0,35
7,180630001.0,CR 800 N and CR 275 E,Hendricks,NaN,39.876944,-86.473889,NaN,Site began 04/01/2004,66,56,59.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/29/2007
8,180630002.0,Pittsboro,Hendricks,Pittsboro,39.863367,-86.470539,NaN,Site began 04/01/2004,43,54,36.0,52.0,45,24,NaN,NaN,NaN,NaN,Site discontinued 03/26/2009
9,180630003.0,Lizton - TriWest High School,Hendricks,Lizton,39.880871,-86.541930,NaN,Site began 04/01/2004,38,52,36.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/29/2007
10,180730002.0,Wheatfield,Jasper,Wheatfield,41.187854,-87.053571,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/28/2002
11,180730003.0,Asphaltum Substation,Jasper,NaN,41.135854,-86.987773,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/28/2002
12,180890006.0,East Chicago - Franklin/Washington School,Lake,East Chicago,41.636111,-87.440833,36,37,50,69,44.0,101.0,50,50,61.0,54.0,47.0,44.0,52
13,180890022.0,Gary - IITRI (1st Max),Lake,Gary,41.606667,-87.304722,191,228,245,214,106.0,134.0,165,83,73.0,104.0,220.0,127.0,138
14,NaN,Gary - IITRI (2nd Max),NaN,NaN,NaN,NaN,114,166,177,183,NaN,NaN,117,NaN,NaN,NaN,153.0,NaN,NaN
15,NaN,Gary- IITRI (3rd Max),NaN,NaN,NaN,NaN,NaN,162,155,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Gary- IITRI (4th Max),NaN,NaN,NaN,NaN,NaN,140,145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,180890023.0,East Chicago - Aldis St.,Lake,East Chicago,41.652778,-87.439444,57,52,51,59,42.0,50.0,48,71,82.0,83.0,67.0,NaN,Site discontinued 10/30/2012
18,180890031.0,Gary - Madison St,Lake,Gary,41.598505,-87.342991,NaN,NaN,Site began 07/01/2005,64,54.0,77.0,59,64,79.0,82.0,88.0,84.0,66
19,180890034.0,East Chicago-Marina,Lake,East Chicago,41.653580,-87.435650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43
20,180891016.0,Gary - Federal Building,Lake,Gary,41.600278,-87.334722,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 09/29/2002
21,180892010.0,Hammond - Clark HS,Lake,Hammond,41.678333,-87.508333,41,36,35,59,29.0,45.0,46,42,65.0,66.0,44.0,NaN,Site discontinued 12/29/2012
22,180950009.0,Anderson - W 5th St,Madison,Anderson,40.111975,-85.679952,58,45,38,50,41.0,47.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/30/2005
23,180970042.0,Indpls - Mann Road,Marion,Indianapolis,39.646254,-86.248784,42,38,35,42,35.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2007
24,180970043.0,Indpls - West St,Marion,Indianapolis,39.744957,-86.166496,52,52,98,65,57.0,59.0,55,56,104.0,68.0,74.0,59.0,59
25,180970060.0,Indpls - S Holt Rd,Marion,Indianapolis,39.738316,-86.227762,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/28/2002
26,180970066.0,Indpls - English Ave,Marion,Indianapolis,39.760437,-86.108848,50,56,45,60,51.0,57.0,45,26,NaN,NaN,NaN,NaN,Site discontinued 02/12/2009
27,180970071.0,Indpls- Drover,Marion,Indianapolis,39.747931,-86.175812,52,61,51,83,56.0,58.0,53,67,100.0,68.0,52.0,NaN,Site discontinued 12/29/2012
28,180970073.0,Indpls - E 16th St,Marion,Indianapolis,39.789167,-86.060833,45,43,37,50,49.0,50.0,45,43,43.0,49.0,NaN,NaN,Site discontinued 12/29/2011
29,180970078.0,Indpls- Washington Park,Marion,Indianapolis,39.811097,-86.114469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 07/21/2011,53.0,52.0,55.0,44.0,44
30,180970083.0,Indpls - E Michigan St,Marion,Indianapolis,39.774979,-86.122020,46,50,46,52,40.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2007
31,180970084.0,Indpls - School 21,Marion,Indianapolis,39.759083,-86.115556,NaN,NaN,NaN,NaN,NaN,NaN,Site began 02/15/2009,49,66.0,50.0,43.0,42.0,Site discontinued 12/30/2013
32,181230006.0,Tell City - Old Brush Fork Rd,Perry,Tell City,37.994240,-86.763445,130,58,101,79,79.0,90.0,71,19,NaN,NaN,NaN,NaN,Site discontinued 04/19/2009
33,181230007.0,Tell City - Waupaca Foundry,Perry,Tell City,37.983883,-86.772190,48,58,52,55,54.0,61.0,43,27,NaN,NaN,NaN,NaN,Site discontinued 04/19/2009
34,181270022.0,Bethlehem Steel-East Office,Porter,NaN,41.633333,-87.102778,39,39,28,41,46.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2007
35,181270023.0,Portage - Hwy 12 (1st Max),Porter,Portage,41.616618,-87.146959,82,75,302,191,191.0,80.0,112,74,83.0,95.0,230.0,130.0,73
36,NaN,Portage - Hwy 12 (2nd Max),NaN,NaN,NaN,NaN,NaN,NaN,220,133,121.0,NaN,NaN,NaN,NaN,NaN,126.0,NaN,NaN
37,NaN,Portage - Hwy 12 (3rd Max),NaN,NaN,NaN,NaN,NaN,NaN,154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,181270024.0,Ogden Dunes,Porter,Ogden Dunes,41.617500,-87.199167,38,34,32,54,65.0,44.0,56,53,53.0,44.0,33.0,41.0,33
39,181330001.0,Greencastle,Putnam,Greencastle,39.623056,-86.854444,70,73,52,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 03/29/2005
40,181410015.0,South Bend - Shields Dr,St Joseph,South Bend,41.696692,-86.214683,NaN,NaN,NaN,Site began 06/01/2006,33.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2007
41,181411008.0,South Bend - Angela & Eddy,St Joseph,South Bend,41.693611,-86.236667,Site began 01/01/2003,42,46,104,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 05/29/2006
42,181412004.0,South Bend - LaSalle HS,St Joseph,South Bend,41.694444,-86.287500,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2002
43,181630006.0,Evansville - Civic Center,Vanderburgh,Evansville,37.971727,-87.567236,68,49,55,62,55.0,51.0,55,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2008
44,181630012.0,Evansville - Mill Rd,Vanderburgh,Evansville,38.021727,-87.569458,Site began 07/01/2003,52,43,57,53.0,49.0,42,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/26/2008
45,181630014.0,Evansville - Illinois St,Vanderburgh,Evansville,37.979167,-87.600000,66,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/26/2003
46,181630021.0,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,NaN,NaN,NaN,NaN,NaN,NaN,Site began 10/21/2009,41,42.0,43.0,33.0,30.0,41
47,181670018.0,Terre Haute - Lafayette Ave,Vigo,Terre Haute,39.486111,-87.401389,63,58,47,62,41.0,57.0,47,46,44.0,49.0,37.0,35.0,58
48,181670020.0,Terre Haute - Hulman St,Vigo,Terre Haute,39.448611,-87.391944,44,49,42,58,60.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 09/27/2007
49,181770012.0,Richmond - West Side of Plant,Wayne,Richmond,39.834444,-84.917222,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 10/29/2002
50,181770013.0,Richmond - NE Side of Plant,Wayne,Richmond,39.836111,-84.914167,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 10/29/2002
51,181830001.0,SDI - West Site (1st Max),Whitley,NaN,41.122988,-85.342146,110,72,56,100,100.0,151.0,148,70,46.0,NaN,NaN,NaN,Site discontinued 02/01/2010
52,181830002.0,SDI - East Site (1st Max),Whitley,NaN,41.124817,-85.356633,58,61,82,74,106.0,147.0,238,84,52.0,NaN,NaN,NaN,Site discontinued 02/01/2010
53,NaN,SDI - East Site (2nd Max),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123,NaN,NaN,NaN,NaN,NaN,NaN

In [169]:
pm10_melted = pm10_data.melt(id_vars=['Site #', 'Site Name', 'County', 'City', 'Latitude', 'Longitude'], 
                    var_name='Year', value_name='Value')

In [170]:
pm10_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030004.0,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094742,-85.101876,2002,38
1,180190005.0,Jeffersonville - Spring St,Clark,Jeffersonville,38.270833,-85.740278,2002,43
2,180190006.0,Jeffersonville - Walnut St,Clark,Jeffersonville,38.277675,-85.740153,2002,Site began 06/23/2003
3,180190007.0,Jefferson - Jeffboat,Clark,Jeffersonville,38.278666,-85.724350,2002,Site began 10/01/2003
4,180270004.0,Washington,Daviess,Washington,38.639167,-87.222222,2002,55
...,...,...,...,...,...,...,...,...
697,181770012.0,Richmond - West Side of Plant,Wayne,Richmond,39.834444,-84.917222,2014,Site discontinued 10/29/2002
698,181770013.0,Richmond - NE Side of Plant,Wayne,Richmond,39.836111,-84.914167,2014,Site discontinued 10/29/2002
699,181830001.0,SDI - West Site (1st Max),Whitley,NaN,41.122988,-85.342146,2014,Site discontinued 02/01/2010
700,181830002.0,SDI - East Site (1st Max),Whitley,NaN,41.124817,-85.356633,2014,Site discontinued 02/01/2010
701,NaN,SDI - East Site (2nd Max),NaN,NaN,NaN,NaN,2014,NaN

In [171]:
pm10_melted.isnull().sum()

Site #        78
Site Name      0
County        78
City         143
Latitude      78
Longitude     78
Year           0
Value        333
dtype: int64

In [172]:
pm10_melted[pm10_melted.isnull().any(axis=1)]

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
7,180630001.0,CR 800 N and CR 275 E,Hendricks,NaN,39.876944,-86.473889,2002,NaN
8,180630002.0,Pittsboro,Hendricks,Pittsboro,39.863367,-86.470539,2002,NaN
9,180630003.0,Lizton - TriWest High School,Hendricks,Lizton,39.880871,-86.541930,2002,NaN
11,180730003.0,Asphaltum Substation,Jasper,NaN,41.135854,-86.987773,2002,51
14,NaN,Gary - IITRI (2nd Max),NaN,NaN,NaN,NaN,2002,114
...,...,...,...,...,...,...,...,...
684,NaN,Portage - Hwy 12 (2nd Max),NaN,NaN,NaN,NaN,2014,NaN
685,NaN,Portage - Hwy 12 (3rd Max),NaN,NaN,NaN,NaN,2014,NaN
699,181830001.0,SDI - West Site (1st Max),Whitley,NaN,41.122988,-85.342146,2014,Site discontinued 02/01/2010
700,181830002.0,SDI - East Site (1st Max),Whitley,NaN,41.124817,-85.356633,2014,Site discontinued 02/01/2010
701,NaN,SDI - East Site (2nd Max),NaN,NaN,NaN,NaN,2014,NaN

In [173]:
pm10_melted_cleaned = pm10_melted[pm10_melted.isnull().sum(axis=1) == pm10_melted['Value'].isnull()]

In [174]:
pm10_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030004.0,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094742,-85.101876,2002,38
1,180190005.0,Jeffersonville - Spring St,Clark,Jeffersonville,38.270833,-85.740278,2002,43
2,180190006.0,Jeffersonville - Walnut St,Clark,Jeffersonville,38.277675,-85.740153,2002,Site began 06/23/2003
3,180190007.0,Jefferson - Jeffboat,Clark,Jeffersonville,38.278666,-85.724350,2002,Site began 10/01/2003
4,180270004.0,Washington,Daviess,Washington,38.639167,-87.222222,2002,55
...,...,...,...,...,...,...,...,...
697,181770012.0,Richmond - West Side of Plant,Wayne,Richmond,39.834444,-84.917222,2014,Site discontinued 10/29/2002
698,181770013.0,Richmond - NE Side of Plant,Wayne,Richmond,39.836111,-84.914167,2014,Site discontinued 10/29/2002
699,181830001.0,SDI - West Site (1st Max),Whitley,NaN,41.122988,-85.342146,2014,Site discontinued 02/01/2010
700,181830002.0,SDI - East Site (1st Max),Whitley,NaN,41.124817,-85.356633,2014,Site discontinued 02/01/2010
701,NaN,SDI - East Site (2nd Max),NaN,NaN,NaN,NaN,2014,NaN

In [175]:
pm10_melted.dropna(subset=['Latitude', 'Longitude'], inplace=True)

In [176]:
pm10_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030004.0,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094742,-85.101876,2002,38
1,180190005.0,Jeffersonville - Spring St,Clark,Jeffersonville,38.270833,-85.740278,2002,43
2,180190006.0,Jeffersonville - Walnut St,Clark,Jeffersonville,38.277675,-85.740153,2002,Site began 06/23/2003
3,180190007.0,Jefferson - Jeffboat,Clark,Jeffersonville,38.278666,-85.724350,2002,Site began 10/01/2003
4,180270004.0,Washington,Daviess,Washington,38.639167,-87.222222,2002,55
...,...,...,...,...,...,...,...,...
696,181670020.0,Terre Haute - Hulman St,Vigo,Terre Haute,39.448611,-87.391944,2014,Site discontinued 09/27/2007
697,181770012.0,Richmond - West Side of Plant,Wayne,Richmond,39.834444,-84.917222,2014,Site discontinued 10/29/2002
698,181770013.0,Richmond - NE Side of Plant,Wayne,Richmond,39.836111,-84.914167,2014,Site discontinued 10/29/2002
699,181830001.0,SDI - West Site (1st Max),Whitley,NaN,41.122988,-85.342146,2014,Site discontinued 02/01/2010
700,181830002.0,SDI - East Site (1st Max),Whitley,NaN,41.124817,-85.356633,2014,Site discontinued 02/01/2010

In [177]:
pm10_melted[pm10_melted['City'].isnull()]['City'].unique()

array([nan], dtype=object)

In [178]:
pm10_melted['Value'].unique()

array([38, 43, 'Site began 06/23/2003', 'Site began 10/01/2003', 55, 109,
       52, nan, 50, 51, 36, 191, 57, 41, 58, 42, 47, 45, 46, 130, 48, 39,
       82, 70, 'Site began 01/01/2003', 68, 'Site began 07/01/2003', 66,
       63, 44, 110, 53, 67, 'Site began 04/01/2004', 37, 228, 56, 61, 75,
       34, 73, 49, 72, 81, 245, 'Site began 07/01/2005', 35, 98, 101, 28,
       302, 32, 59, 54, 69, 214, 64, 65, 60, 83, 79,
       'Site began 06/01/2006', 104, 62, 100, 74, 106.0, 29.0, 40.0, 33.0,
       77.0, 134.0, 90.0, 80.0, 151.0, 147.0, 165,
       'Site began 02/15/2009', 71, 112, 'Site began 10/21/2009', 148,
       238, 24, 26, 'Site began 07/21/2011', 19, 27, 84, 95.0, 31.0,
       220.0, 88.0, 230.0, 30.0, 127.0, 'Site discontinued 12/08/2007',
       'Site discontinued 06/26/2003', 'Site discontinued 07/31/2004',
       'Site discontinued 06/23/2003', 'Site discontinued 10/31/2002',
       'Site discontinued 06/29/2007', 'Site discontinued 03/26/2009',
       'Site discontinued 12/28/2002', 138,
       'Site discontinued 10/30/2012', 'Site discontinued 09/29/2002',
       'Site discontinued 12/29/2012', 'Site discontinued 12/30/2005',
       'Site discontinued 12/26/2007', 'Site discontinued 02/12/2009',
       'Site discontinued 12/29/2011', 'Site discontinued 12/30/2013',
       'Site discontinued 04/19/2009', 'Site discontinued 03/29/2005',
       'Site discontinued 05/29/2006', 'Site discontinued 12/26/2002',
       'Site discontinued 12/26/2008', 'Site discontinued 09/27/2007',
       'Site discontinued 10/29/2002', 'Site discontinued 02/01/2010'],
      dtype=object)

In [179]:
pm10_melted['Value'] = pd.to_numeric(pm10_melted['Value'], errors='coerce')

In [180]:
pm10_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030004.0,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094742,-85.101876,2002,38.0
1,180190005.0,Jeffersonville - Spring St,Clark,Jeffersonville,38.270833,-85.740278,2002,43.0
2,180190006.0,Jeffersonville - Walnut St,Clark,Jeffersonville,38.277675,-85.740153,2002,NaN
3,180190007.0,Jefferson - Jeffboat,Clark,Jeffersonville,38.278666,-85.724350,2002,NaN
4,180270004.0,Washington,Daviess,Washington,38.639167,-87.222222,2002,55.0
...,...,...,...,...,...,...,...,...
696,181670020.0,Terre Haute - Hulman St,Vigo,Terre Haute,39.448611,-87.391944,2014,NaN
697,181770012.0,Richmond - West Side of Plant,Wayne,Richmond,39.834444,-84.917222,2014,NaN
698,181770013.0,Richmond - NE Side of Plant,Wayne,Richmond,39.836111,-84.914167,2014,NaN
699,181830001.0,SDI - West Site (1st Max),Whitley,NaN,41.122988,-85.342146,2014,NaN
700,181830002.0,SDI - East Site (1st Max),Whitley,NaN,41.124817,-85.356633,2014,NaN

In [181]:
pm10_melted.isnull().sum()

Site #         0
Site Name      0
County         0
City          65
Latitude       0
Longitude      0
Year           0
Value        320
dtype: int64

In [182]:
pm10_melted.dropna(subset=['City'], inplace=True)

In [183]:
pm10_melted.isnull().sum()

Site #         0
Site Name      0
County         0
City           0
Latitude       0
Longitude      0
Year           0
Value        284
dtype: int64

### PM25 Data Cleaning

In [184]:
pm25_data

,Site #,Site Name,County,City,Latitude,Longitude,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024**
0,180030004,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094722,-85.101944,10.70,10.00,8.60,8.16,9.1,8.95,8.33,8.6,NaN,NaN,Site discontinued 09/30/2021
1,180030015,Fort Wayne - Coliseum,Allen,Fort Wayne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,site began 10/30/2023,8.37,8.5
2,180050008,Columbus - Rocky Ford Drive,Bartholomew,Columbus,39.237457,-85.891332,10.70,9.50,8.20,7,7.5,6.89,6.67,7.8,6.65,8.41,6.9
3,180190006,Jeffersonville - Walnut St.,Clark,Jeffersonville,38.277675,-85.740153,11.93,10.71,9.28,8.68,9.16,8.39,NaN,NaN,NaN,NaN,Site discontinued 05/18/2019
4,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,9.49,8.83,7.85,7.37,7.94,7.20,7.07,8.2,7.3,NaN,Site discontinued 12/31/2022
5,180190010,Jeffersonville - Bates-Bowyer Ave,Clark,Jeffersonville,38.288191,-85.741337,NaN,NaN,NaN,NaN,Site began 05/21/2019,8.50,8.80,9.9,9.2,10.50,7.7
6,180350006,Muncie - Central HS,Delaware,Muncie,40.201111,-85.388056,10.35,8.95,7.73,7.69,8.34,8.34,7.96,8.9,7.54,8.30,6.9
7,180372001,Jasper - Post Office,Dubois,Jasper,38.391389,-86.929167,11.13,9.71,8.69,8.29,8.88,8.43,8.40,9.4,8.61,8.60,7.3
8,180390008,Elkhart - Prairie St,Elkhart,Elkhart,41.656905,-85.968371,11.39,10.27,8.50,7.8,8.2,8.10,8.21,8.6,8.54,9.40,7.2
9,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 01/11/2023,8.40,6
10,180431004,New Albany,Floyd,New Albany,38.308056,-85.834167,11.70,10.00,7.60,8.7,9.2,NaN,NaN,NaN,NaN,NaN,Site discontinued 01/26/2018
11,180550001,Plummer,Greene,NaN,38.985578,-86.990120,9.93,8.73,7.84,7.68,8.17,7.74,7.49,8.4,7.13,8.30,6.6
12,180570007,Fishers,Hamilton,Fishers,39.960884,-85.939546,9.70,8.80,8.50,7.6,8.1,8.30,7.00,8.1,7.14,8.50,6.2
13,180570008,Carmel - Hazel Dell Parkway,Hamilton,Carmel,39.928804,-86.078775,NaN,NaN,NaN,NaN,Site began 01/10/2019,10.15,9.36,9.9,10.1,9.90,7.5
14,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,9.88,8.10,7.27,7.22,7.9,7.68,7.30,8.1,7.14,9.20,6.6
15,180670004,Kokomo - E. Vaile Ave,Howard,Kokomo,40.481347,-86.109688,10.40,11.40,8.90,8.2,7.9,7.27,6.69,8.1,7.3,8.90,7
16,180890006,East Chicago - Franklin/Washington Sch,Lake,East Chicago,41.636111,-87.440833,10.91,10.55,8.62,8.73,9.46,8.82,8.82,9.5,8.28,9.80,6.6
17,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,12.06,10.26,8.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,180890026,Gary - Burr St,Lake,Gary,41.573056,-87.405833,12.51,10.92,9.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,180890031,Gary - Madison St,Lake,Gary,41.598505,-87.342991,11.70,10.00,8.67,8.9,10.65,9.30,8.68,10.8,9.55,11.00,8.4
20,180890034,East Chicago - Marina,Lake,East Chicago,41.653501,-87.435561,NaN,NaN,NaN,NaN,Site began 10/28/2019,11.20,8.60,9.7,8.2,10.80,8.1
21,180890036,Hammond-167th St,Lake,Gary,41.594408,-87.495041,NaN,NaN,NaN,Site began 02/01/2018,9,9.50,8.20,8.8,7.8,10.40,7.1
22,180892004,Hammond - Purdue,Lake,Hammond,41.585278,-87.474444,11.51,9.90,8.11,8.2,8.78,NaN,NaN,NaN,NaN,NaN,Site discontinued 02/01/2018
23,180892010,Hammond - Clark HS,Lake,Hammond,41.678333,-87.508333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/29/2012
24,180910011,Michigan City - Marsh Elem. Sch.,LaPorte,Michigan City,41.706944,-86.891111,9.99,9.10,7.66,7.44,7.43,7.91,8.05,8.3,7.91,8.70,6.6
25,180950011,Anderson - Eastside Elem,Madison,Anderson,40.125556,-85.652222,10.37,8.70,8.00,8.4,8.6,8.40,7.80,8.8,7.9,9.80,6.9
26,180970043,Indpls - West St.,Marion,Indianapolis,39.744957,-86.166496,12.60,11.40,9.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,11.41,9.30,9.30,8.1,9.5,9.60,9.30,10.5,9.6,11.40,7.8
28,180970081,Indpls - W. 18th St.,Marion,Indianapolis,39.788903,-86.214628,12.25,11.17,9.80,9.55,10.6,10.60,9.90,11.4,10.5,13.40,9.7
29,180970083,Indpls - E. Michigan St.,Marion,Indianapolis,39.774944,-86.122053,11.82,10.94,10.42,9.24,9.68,9.54,NaN,NaN,NaN,NaN,Site discontinued 12/29/2019
30,180970084,Indpls - School 21,Marion,Indianapolis,39.759083,-86.115556,11.96,10.80,9.13,9.18,9.6,9.49,9.30,9.9,9.23,10.10,8
31,180970087,Indpls- I-70 E,Marion,Indianapolis,39.787933,-86.130880,12.85,11.53,9.90,10.3,10.8,12.20,10.20,11.2,10.8,13.70,8.9
32,181050003,Bloomington - Binford,Monroe,Bloomington,39.159444,-86.504722,10.03,8.69,7.58,7.52,8.7,7.30,7.40,8.2,7,8.60,6.5
33,181270024,Ogden Dunes,Porter,Ogden Dunes,41.617500,-87.199167,11.90,9.10,7.50,7.4,8.1,8.36,7.50,8.8,8.5,9.70,6.5
34,181410015,South Bend - Shields Dr.,St Joseph,South Bend,41.696692,-86.214683,11.50,10.60,9.30,8,9.4,8.30,8.40,9.2,8.7,10.30,7.6
35,181470009,Dale,Spencer,Dale,38.167500,-86.983333,10.76,9.41,8.47,8.29,8.5,8.00,8.00,8.7,7.9,8.70,6.4
36,181570008,Lafayette - Greenbush St,Tippecanoe,Lafayette,40.431639,-86.852500,10.72,9.20,7.50,8.5,8.3,8.80,9.30,8.7,7.16,9.30,7.2
37,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,11.25,9.58,8.70,8.4,8.6,7.80,7.10,9.5,8.6,10.10,8.8
38,181630016,Evansville - U of E,Vanderburgh,Evansville,37.974444,-87.532222,11.18,9.98,8.91,8.71,9.3,8.70,9.06,9.6,8.8,8.90,6.9
39,181630023,Evansville - E. Walnut,Vanderburgh,Evansville,37.974460,-87.558018,11.18,10.10,9.05,8.89,9.24,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2019
40,181670018,Terre Haute - Lafayette Ave,Vigo,Terre Haute,39.486111,-87.401389,11.06,10.10,9.20,9.2,8.4,9.60,8.10,9.6,8.44,10.50,8.7
41,181830003,Larwill,Whitley,Larwill,41.169646,-85.629292,9.73,9.15,7.65,7.6,7.98,8.10,7.47,8.4,7.6,9.80,6.6

In [185]:
pm25_melted = pm25_data.melt(id_vars=['Site #', 'Site Name', 'County', 'City', 'Latitude', 'Longitude'], 
                    var_name='Year', value_name='Value')

In [186]:
pm25_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030004,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094722,-85.101944,2014,10.7
1,180030015,Fort Wayne - Coliseum,Allen,Fort Wayne,NaN,NaN,2014,NaN
2,180050008,Columbus - Rocky Ford Drive,Bartholomew,Columbus,39.237457,-85.891332,2014,10.7
3,180190006,Jeffersonville - Walnut St.,Clark,Jeffersonville,38.277675,-85.740153,2014,11.93
4,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2014,9.49
...,...,...,...,...,...,...,...,...
457,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,2024**,8.8
458,181630016,Evansville - U of E,Vanderburgh,Evansville,37.974444,-87.532222,2024**,6.9
459,181630023,Evansville - E. Walnut,Vanderburgh,Evansville,37.974460,-87.558018,2024**,Site discontinued 12/31/2019
460,181670018,Terre Haute - Lafayette Ave,Vigo,Terre Haute,39.486111,-87.401389,2024**,8.7
461,181830003,Larwill,Whitley,Larwill,41.169646,-85.629292,2024**,6.6

In [187]:
pm25_melted.isnull().sum()

Site #        0
Site Name     0
County        0
City         33
Latitude     11
Longitude    11
Year          0
Value        91
dtype: int64

In [188]:
pm25_melted.dropna(subset=['Latitude', 'Longitude'], inplace=True)

In [189]:
pm25_melted.isnull().sum()

Site #        0
Site Name     0
County        0
City         33
Latitude      0
Longitude     0
Year          0
Value        83
dtype: int64

In [190]:
pm25_melted[pm25_melted['City'].isnull()].drop_duplicates()

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
4,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2014,9.49
11,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2014,9.93
14,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2014,9.88
46,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2015,8.83
53,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2015,8.73
56,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2015,8.1
88,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2016,7.85
95,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2016,7.84
98,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2016,7.27
130,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2017,7.37
137,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2017,7.68
140,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2017,7.22
172,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2018,7.94
179,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2018,8.17
182,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2018,7.9
214,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2019,7.2
221,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2019,7.74
224,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2019,7.68
256,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2020,7.07
263,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2020,7.49
266,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2020,7.3
298,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2021,8.2
305,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2021,8.4
308,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2021,8.1
340,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2022,7.3
347,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2022,7.13
350,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2022,7.14
382,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2023,NaN
389,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2023,8.3
392,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2023,9.2
424,180190008,Charlestown State Park,Clark,NaN,38.393833,-85.664167,2024**,Site discontinued 12/31/2022
431,180550001,Plummer,Greene,NaN,38.985578,-86.990120,2024**,6.6
434,180650003,Mechanicsburg,Henry,NaN,40.011667,-85.523611,2024**,6.6

In [191]:
site_to_city = {
    'Mechanicsburg': 'Henry', 
    'Charlestown State Park': 'Charlestown', 
    'Plummer': 'Plummer'
}
pm25_melted.loc[pm25_melted['Site Name'].isin(site_to_city.keys()), 'City'] = pm25_melted['Site Name'].map(site_to_city)

In [192]:
pm25_melted[pm25_melted['City'].isnull()]

Empty DataFrame
Columns: [Site #, Site Name, County, City, Latitude, Longitude, Year, Value]
Index: []

In [193]:
pm25_melted['Value'].unique()

array([10.7, 11.93, 9.49, nan, 10.35, 11.13, 11.39, 11.7, 9.93, 9.7, 9.88,
       10.4, 10.91, 12.06, 12.51, 11.51, 9.99, 10.37, 12.6, 11.41, 12.25,
       11.82, 11.96, 12.85, 10.03, 11.9, 11.5, 10.76, 10.72, 11.25, 11.18,
       11.06, 9.73, 10.0, 9.5, 10.71, 8.83, 8.95, 9.71, 10.27, 8.73, 8.8,
       8.1, 11.4, 10.55, 10.26, 10.92, 9.9, 9.1, 8.7, 9.3, 11.17, 10.94,
       10.8, 11.53, 8.69, 10.6, 9.41, 9.2, 9.58, 9.98, 10.1, 9.15, 8.6,
       8.2, 9.28, 7.85, 7.73, 8.5, 7.6, 7.84, 7.27, 8.9, 8.62, 8.67, 8.11,
       7.66, 8.0, 9.8, 10.42, 9.13, 7.58, 7.5, 8.47, 8.91, 9.05, 7.65,
       8.16, 7, 8.68, 7.37, 7.69, 8.29, 7.8, 7.68, 7.22,
       'Site began 02/01/2018', 7.44, 8.4, 9.55, 9.24, 9.18, 10.3, 7.52,
       7.4, 8.71, 8.89, 9.16, 7.94, 'Site began 05/21/2019', 8.34, 8.88,
       8.17, 'Site began 01/10/2019', 7.9, 9.46, 10.65,
       'Site began 10/28/2019', 9, 8.78, 7.43, 9.68, 9.6, 9.4, 8.3, 7.98,
       6.89, 8.39, 7.2, 8.43, 7.74, 10.15, 8.82, 11.2, 7.91, 9.54, 12.2,
       7.3, 8.36, 8.33, 6.67, 7.07, 7.96, 8.21, 7.49, 9.36, 6.69, 8.05,
       10.2, 7.1, 9.06, 7.47, 10.5, 6.65, 7.54, 8.61, 8.54,
       'Site began 01/11/2023', 7.13, 7.14, 8.28, 9.23, 7.16, 8.44, 8.41,
       11.0, 13.4, 13.7, 'Site discontinued 09/30/2021', 6.9,
       'Site discontinued 05/18/2019', 'Site discontinued 12/31/2022',
       7.7, 6, 'Site discontinued 01/26/2018', 6.6, 6.2,
       'Site discontinued 02/01/2018', 'Site discontinued 12/29/2012',
       'Site discontinued 12/29/2019', 6.5, 6.4,
       'Site discontinued 12/31/2019'], dtype=object)

In [194]:
pm25_melted['Value'] = pd.to_numeric(pm25_melted['Value'], errors='coerce')

In [195]:
pm25_melted

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180030004,Fort Wayne - Beacon St,Allen,Fort Wayne,41.094722,-85.101944,2014,10.70
2,180050008,Columbus - Rocky Ford Drive,Bartholomew,Columbus,39.237457,-85.891332,2014,10.70
3,180190006,Jeffersonville - Walnut St.,Clark,Jeffersonville,38.277675,-85.740153,2014,11.93
4,180190008,Charlestown State Park,Clark,Charlestown,38.393833,-85.664167,2014,9.49
5,180190010,Jeffersonville - Bates-Bowyer Ave,Clark,Jeffersonville,38.288191,-85.741337,2014,NaN
...,...,...,...,...,...,...,...,...
457,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,2024**,8.80
458,181630016,Evansville - U of E,Vanderburgh,Evansville,37.974444,-87.532222,2024**,6.90
459,181630023,Evansville - E. Walnut,Vanderburgh,Evansville,37.974460,-87.558018,2024**,NaN
460,181670018,Terre Haute - Lafayette Ave,Vigo,Terre Haute,39.486111,-87.401389,2024**,8.70
461,181830003,Larwill,Whitley,Larwill,41.169646,-85.629292,2024**,6.60

### SO2 Data Cleaning

In [196]:
so2_data

,Site ID,Site Name,County,City,Latitude,Longitude,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024*
0,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 01/11/2023,4.6,5
1,180431004,New Albany-Green Valley Elem. Sch.,Floyd,New Albany,38.308056,-85.834167,32.0,20.5,43.8,25.5,11.2,8.2,9,4.6,4.5,3.8,6.5,NaN,Site discontinued 01/04/2023
2,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,47.0,43.2,53.1,35.4,29.2,36.2,25.6,35.1,31.5,32.2,20.4,23.5,38.4
3,180890034,East Chicago-Marina,Lake,East Chicago,41.653446,-87.435435,NaN,NaN,NaN,NaN,NaN,NaN,Site began 11/01/2019,14.2,22.7,18.5,10,19.3,12.9
4,180892008,Hammond - 141st St.,Lake,Hammond,41.639444,-87.493611,28.1,23.7,20.2,25.9,21,18.4,19.1,20.4,25,19.3,13.7,21.2,17.4
5,180970057,Indpls - Harding St.,Marion,Indianapolis,39.749019,-86.186314,91.5,78.1,105.6,54.3,14.6,6.3,3.5,4.7,6.1,7.6,6.6,NaN,Site discontinued 12/31/2022
6,180970078,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,61.1,69.7,80.0,50.2,6.4,3.2,3.2,2.7,3.7,2.8,2.7,2.6,1.8
7,181630021,Evansville - Buena Vista,Vanderburgh,Evansville,38.013333,-87.577778,16.5,18.6,32.3,18.1,11.2,8.6,11.4,8.0,6.8,8.8,10.2,6.7,5.8
8,181670018,Terre Haute - Lafayette Ave,Vigo,Terre Haute,39.486111,-87.401389,72.5,79.1,85.0,71.3,57.6,3.0,4,4.1,3.7,3.6,3.2,3.6,3
9,181730011,Dayville,Warrick,Newburgh,37.954444,-87.321667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site began 01/01/2021,21.3,22.7,19.6,18.2
10,180270002,AES/ IPL Petersburg- West off of SR 57,Daviess,NaN,38.572829,-87.214724,78.0,150.0,107.0,93.0,22,16.4,13.2,12.3,11,8.7,NaN,NaN,Site discontinued 06/30/2021
11,180430004,0.2 mile North of Bald Knob Rd at Wlky Tower,Floyd,NaN,38.367967,-85.832955,38.0,30.0,65.0,28.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/30/2016
12,180450001,"N of SR 234, E of Wabash River",Fountain,NaN,39.964200,-87.421398,30.0,34.0,22.0,19.0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 06/30/2016
13,180510002,Duke Energy - E. Mount Carmel,Gibson,NaN,38.392832,-87.748353,76.0,64.0,77.0,59.0,71,47.9,49.2,41.3,59.3,37.2,33.8,21.9,30.9
14,180730002,Wheatfield - Center St,Jasper,Wheatfield,41.187854,-87.053571,33.0,40.0,18.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2015
15,180910005,Michigan City - 341 W 4th St,LaPorte,Michigan City,41.717022,-86.907743,21.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontinued 12/31/2014
16,181091001,Eagle Valley - High Street,Morgan,Martinsville,39.515039,-86.391643,82.0,64.0,90.0,55.8,23.4,46.7,54.5,47.6,NaN,NaN,NaN,NaN,Site discontinued 06/12/2019
17,181250005,Petersburg- Arda Lane,Pike,NaN,38.519148,-87.249794,140.2,169.4,156.7,74.2,26.1,23.5,19,13.0,NaN,NaN,NaN,NaN,Site discontinued 08/22/2019
18,181270011,Dune Acres Substation,Porter,Dune Acres,41.634109,-87.101478,36.0,36.0,27.0,38.8,30.8,29.0,23.4,31.6,39,NaN,NaN,NaN,Site discontinued 04/30/2020
19,181270028,Clevland Cliffs - Burns Harbor,Porter,NaN,41.635404,-87.150567,NaN,NaN,NaN,NaN,Site began 01/01/2017,33.2,27.9,78.8,80.5,72.5,44.9,79.4,57.4
20,181770006,Richmond - S 9th St,Wayne,Richmond,39.812256,-84.889927,22.4,14.3,7.0,35.0,34.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Site discontined 12/31/2016
21,171850001,Duke Energy-Mount Carmel,"Wabash, IL",NaN,38.397789,-87.773853,89.0,55.0,53.0,43.0,42,32.0,37,31.0,49,21.0,24.9,10.2,18

In [197]:
so2_melted = so2_data.melt(id_vars=['Site ID', 'Site Name', 'County', 'City', 'Latitude', 'Longitude'], 
                    var_name='Year', value_name='Value')

In [198]:
so2_melted

,Site ID,Site Name,County,City,Latitude,Longitude,Year,Value
0,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,2012,NaN
1,180431004,New Albany-Green Valley Elem. Sch.,Floyd,New Albany,38.308056,-85.834167,2012,32.0
2,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,2012,47.0
3,180890034,East Chicago-Marina,Lake,East Chicago,41.653446,-87.435435,2012,NaN
4,180892008,Hammond - 141st St.,Lake,Hammond,41.639444,-87.493611,2012,28.1
...,...,...,...,...,...,...,...,...
281,181250005,Petersburg- Arda Lane,Pike,NaN,38.519148,-87.249794,2024*,Site discontinued 08/22/2019
282,181270011,Dune Acres Substation,Porter,Dune Acres,41.634109,-87.101478,2024*,Site discontinued 04/30/2020
283,181270028,Clevland Cliffs - Burns Harbor,Porter,NaN,41.635404,-87.150567,2024*,57.4
284,181770006,Richmond - S 9th St,Wayne,Richmond,39.812256,-84.889927,2024*,Site discontined 12/31/2016
285,171850001,Duke Energy-Mount Carmel,"Wabash, IL",NaN,38.397789,-87.773853,2024*,18

In [199]:
so2_melted.isnull().sum()

Site ID       0
Site Name     0
County        0
City         91
Latitude      0
Longitude     0
Year          0
Value        81
dtype: int64

In [200]:
so2_melted[so2_melted['City'].isnull()].drop_duplicates()

,Site ID,Site Name,County,City,Latitude,Longitude,Year,Value
10,180270002,AES/ IPL Petersburg- West off of SR 57,Daviess,NaN,38.572829,-87.214724,2012,78.0
11,180430004,0.2 mile North of Bald Knob Rd at Wlky Tower,Floyd,NaN,38.367967,-85.832955,2012,38.0
12,180450001,"N of SR 234, E of Wabash River",Fountain,NaN,39.964200,-87.421398,2012,30.0
13,180510002,Duke Energy - E. Mount Carmel,Gibson,NaN,38.392832,-87.748353,2012,76.0
17,181250005,Petersburg- Arda Lane,Pike,NaN,38.519148,-87.249794,2012,140.2
...,...,...,...,...,...,...,...,...
276,180450001,"N of SR 234, E of Wabash River",Fountain,NaN,39.964200,-87.421398,2024*,Site discontinued 06/30/2016
277,180510002,Duke Energy - E. Mount Carmel,Gibson,NaN,38.392832,-87.748353,2024*,30.9
281,181250005,Petersburg- Arda Lane,Pike,NaN,38.519148,-87.249794,2024*,Site discontinued 08/22/2019
283,181270028,Clevland Cliffs - Burns Harbor,Porter,NaN,41.635404,-87.150567,2024*,57.4
285,171850001,Duke Energy-Mount Carmel,"Wabash, IL",NaN,38.397789,-87.773853,2024*,18

In [201]:
so2_melted[so2_melted['City'].isnull()]['Site Name'].unique()

array(['AES/ IPL Petersburg- West off of SR 57',
       '0.2 mile North of Bald Knob Rd at Wlky Tower',
       'N of SR 234, E of Wabash River', 'Duke Energy - E. Mount Carmel',
       'Petersburg- Arda Lane', 'Clevland Cliffs - Burns Harbor ',
       'Duke Energy-Mount Carmel'], dtype=object)

In [202]:
site_to_city = {
    'AES/ IPL Petersburg- West off of SR 57': 'Petersburg',
    '0.2 mile North of Bald Knob Rd at Wlky Tower': 'Indianapolis',
    'N of SR 234, E of Wabash River': 'Wabash',
    'Duke Energy - E. Mount Carmel': 'Mount Carmel',
    'Petersburg- Arda Lane': 'Petersburg',
    'Clevland Cliffs - Burns Harbor ': 'Burns Harbor',
    'Duke Energy-Mount Carmel': 'Mount Carmel'
}

In [203]:
so2_melted['City'] = so2_melted['Site Name'].map(site_to_city).fillna(so2_melted['City'])

In [204]:
so2_melted.isnull().sum()

Site ID       0
Site Name     0
County        0
City          0
Latitude      0
Longitude     0
Year          0
Value        81
dtype: int64

In [205]:
so2_melted['Value'].unique()

array([nan, 32.0, 47.0, 28.1, 91.5, 61.1, 16.5, 72.5, 78.0, 38.0, 30.0,
       76.0, 33.0, 21.0, 82.0, 140.2, 36.0, 22.4, 89.0, 20.5, 43.2, 23.7,
       78.1, 69.7, 18.6, 79.1, 150.0, 34.0, 64.0, 40.0, 15.0, 169.4, 14.3,
       55.0, 43.8, 53.1, 20.2, 105.6, 80.0, 32.3, 85.0, 107.0, 65.0, 22.0,
       77.0, 18.0, 90.0, 156.7, 27.0, 7.0, 53.0, 25.5, 35.4, 25.9, 54.3,
       50.2, 18.1, 71.3, 93.0, 28.0, 19.0, 59.0, 10.0, 55.8, 74.2, 38.8,
       35.0, 43.0, 11.2, 29.2, 14.6, 6.4, 57.6, 11, 17, 71, 23.4, 26.1,
       30.8, 'Site began 01/01/2017', 34.1, 42, 8.2, 36.2, 18.4, 6.3, 3.2,
       8.6, 3.0, 16.4, 47.9, 46.7, 23.5, 29.0, 33.2, 9, 25.6,
       'Site began 11/01/2019', 19.1, 3.5, 11.4, 4, 13.2, 49.2, 54.5,
       27.9, 37, 4.6, 35.1, 14.2, 20.4, 4.7, 2.7, 8.0, 4.1, 12.3, 41.3,
       47.6, 13.0, 31.6, 78.8, 31.0, 4.5, 31.5, 22.7, 25, 6.1, 3.7, 6.8,
       'Site began 01/01/2021', 59.3, 39, 80.5, 49, 3.8, 32.2, 18.5, 19.3,
       7.6, 2.8, 8.8, 3.6, 21.3, 8.7, 37.2, 'Site began 01/11/2023', 6.5,
       13.7, 6.6, 10.2, 33.8, 44.9, 24.9, 21.2, 2.6, 6.7, 19.6, 21.9,
       79.4, 5, 'Site discontinued 01/04/2023', 38.4, 12.9, 17.4,
       'Site discontinued 12/31/2022', 1.8, 5.8, 18.2,
       'Site discontinued 06/30/2021', 'Site discontinued 06/30/2016',
       30.9, 'Site discontinued 12/31/2015',
       'Site discontinued 12/31/2014', 'Site discontinued 06/12/2019',
       'Site discontinued 08/22/2019', 'Site discontinued 04/30/2020',
       57.4, 'Site discontined 12/31/2016'], dtype=object)

In [206]:
so2_melted['Value'] = pd.to_numeric(so2_melted['Value'], errors='coerce')

In [207]:
so2_melted

,Site ID,Site Name,County,City,Latitude,Longitude,Year,Value
0,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,2012,NaN
1,180431004,New Albany-Green Valley Elem. Sch.,Floyd,New Albany,38.308056,-85.834167,2012,32.0
2,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,2012,47.0
3,180890034,East Chicago-Marina,Lake,East Chicago,41.653446,-87.435435,2012,NaN
4,180892008,Hammond - 141st St.,Lake,Hammond,41.639444,-87.493611,2012,28.1
...,...,...,...,...,...,...,...,...
281,181250005,Petersburg- Arda Lane,Pike,Petersburg,38.519148,-87.249794,2024*,NaN
282,181270011,Dune Acres Substation,Porter,Dune Acres,41.634109,-87.101478,2024*,NaN
283,181270028,Clevland Cliffs - Burns Harbor,Porter,Burns Harbor,41.635404,-87.150567,2024*,57.4
284,181770006,Richmond - S 9th St,Wayne,Richmond,39.812256,-84.889927,2024*,NaN
285,171850001,Duke Energy-Mount Carmel,"Wabash, IL",Mount Carmel,38.397789,-87.773853,2024*,18.0

In [208]:
so2_melted.rename(columns={'Site ID': 'Site #'})

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value
0,180430008,New Albany,Floyd,New Albany,38.317813,-85.833322,2012,NaN
1,180431004,New Albany-Green Valley Elem. Sch.,Floyd,New Albany,38.308056,-85.834167,2012,32.0
2,180890022,Gary - IITRI,Lake,Gary,41.606667,-87.304722,2012,47.0
3,180890034,East Chicago-Marina,Lake,East Chicago,41.653446,-87.435435,2012,NaN
4,180892008,Hammond - 141st St.,Lake,Hammond,41.639444,-87.493611,2012,28.1
...,...,...,...,...,...,...,...,...
281,181250005,Petersburg- Arda Lane,Pike,Petersburg,38.519148,-87.249794,2024*,NaN
282,181270011,Dune Acres Substation,Porter,Dune Acres,41.634109,-87.101478,2024*,NaN
283,181270028,Clevland Cliffs - Burns Harbor,Porter,Burns Harbor,41.635404,-87.150567,2024*,57.4
284,181770006,Richmond - S 9th St,Wayne,Richmond,39.812256,-84.889927,2024*,NaN
285,171850001,Duke Energy-Mount Carmel,"Wabash, IL",Mount Carmel,38.397789,-87.773853,2024*,18.0

In [209]:
so2_melted['Chemical'] = 'SO2'
pb_melted['Chemical'] = 'Pb'
co_melted['Chemical'] = 'CO'
no2_melted['Chemical'] = 'NO2'
pm25_melted['Chemical'] = 'PM2.5'
pm10_melted['Chemical'] = 'PM10'
o3_melted['Chemical'] = 'O3'

Comnining all the dataframes to create a final dataset.

In [210]:
combinedData = pd.concat([co_melted, pb_melted, no2_melted, so2_melted, pm10_melted, pm25_melted, o3_melted], ignore_index=True)

combinedData.head()

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value,Chemical,Latitude,Site ID
0,180890015.0,East Chicago - Post Office,Lake,East Chicago,41.628611,-87.461389,2014,5.3,CO,NaN,NaN
1,180970072.0,Indpls - Illinois St.,Marion,Indianapolis,39.768056,-86.160000,2014,6.2,CO,NaN,NaN
2,180970078.0,Indpls - Washington Park,Marion,Indianapolis,39.811097,-86.114469,2014,1.5,CO,NaN,NaN
3,180970087.0,Indpls - I-70 E,Marion,Indianapolis,39.787933,-86.130880,2014,1.3,CO,NaN,NaN
4,181630022.0,Evansville - Lloyd,Vanderburgh,Evansville,37.977222,-87.596439,2014,5.4,CO,NaN,NaN

In [211]:
combinedData.dropna(subset=['Latitude', 'Longitude'], inplace=True)

In [212]:
combinedData

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value,Chemical,Latitude,Site ID
55,180350009.0,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,NaN,-85.415021,2021,0.02,Pb,40.158417,NaN
56,180890032.0,Gary - 4th Ave,Lake,Gary,NaN,-87.332658,2021,0.01,Pb,41.603582,NaN
57,180890034.0,East Chicago - Marina,Lake,East Chicago,NaN,-87.435561,2021,0.006,Pb,41.653501,NaN
58,180890037.0,Hammond - E. Lakeview St,Lake,Hammond,NaN,-87.494981,2021,0.04,Pb,41.674278,NaN
59,181270027.0,Burns Harbor - Port of Indiana,Porter,Burns Harbor - Port of Indiana,NaN,-87.150367,2021,0.01,Pb,41.635181,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2467,181730008.0,Boonville,Warrick,Boonville,NaN,-87.278333,2024**,0.067,O3,38.051944,NaN
2468,181730009.0,Lynnville,Warrick,Lynnville,NaN,-87.341396,2024**,NaN,O3,38.194501,NaN
2469,181730011.0,Dayville,Warrick,Dayville,NaN,-87.321933,2024**,0.065,O3,37.954450,NaN
2470,170230001.0,West Union,Clark,NaN,NaN,-87.668297,2024**,0.063,O3,39.210857,NaN
2471,260270003.0,Cassopolis,Cass,Cassopolis,NaN,-86.001629,2024**,0.066,O3,41.895570,NaN

In [213]:
combinedData.drop('Site ID', axis=1, inplace=True)

In [214]:
combinedData

,Site #,Site Name,County,City,Latitude,Longitude,Year,Value,Chemical,Latitude
55,180350009.0,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,NaN,-85.415021,2021,0.02,Pb,40.158417
56,180890032.0,Gary - 4th Ave,Lake,Gary,NaN,-87.332658,2021,0.01,Pb,41.603582
57,180890034.0,East Chicago - Marina,Lake,East Chicago,NaN,-87.435561,2021,0.006,Pb,41.653501
58,180890037.0,Hammond - E. Lakeview St,Lake,Hammond,NaN,-87.494981,2021,0.04,Pb,41.674278
59,181270027.0,Burns Harbor - Port of Indiana,Porter,Burns Harbor - Port of Indiana,NaN,-87.150367,2021,0.01,Pb,41.635181
...,...,...,...,...,...,...,...,...,...,...
2467,181730008.0,Boonville,Warrick,Boonville,NaN,-87.278333,2024**,0.067,O3,38.051944
2468,181730009.0,Lynnville,Warrick,Lynnville,NaN,-87.341396,2024**,NaN,O3,38.194501
2469,181730011.0,Dayville,Warrick,Dayville,NaN,-87.321933,2024**,0.065,O3,37.954450
2470,170230001.0,West Union,Clark,NaN,NaN,-87.668297,2024**,0.063,O3,39.210857
2471,260270003.0,Cassopolis,Cass,Cassopolis,NaN,-86.001629,2024**,0.066,O3,41.895570

In [215]:
combinedData.columns

Index(['Site #', 'Site Name', 'County', 'City', 'Latitude ', 'Longitude',
       'Year', 'Value', 'Chemical', 'Latitude'],
      dtype='object')

In [216]:
combinedData.drop('Latitude ', axis=1, inplace=True)

In [217]:
combinedData.shape

(2417, 9)

In [218]:
combinedData

,Site #,Site Name,County,City,Longitude,Year,Value,Chemical,Latitude
55,180350009.0,Muncie - Mt. Pleasant Blvd,Delaware,Muncie,-85.415021,2021,0.02,Pb,40.158417
56,180890032.0,Gary - 4th Ave,Lake,Gary,-87.332658,2021,0.01,Pb,41.603582
57,180890034.0,East Chicago - Marina,Lake,East Chicago,-87.435561,2021,0.006,Pb,41.653501
58,180890037.0,Hammond - E. Lakeview St,Lake,Hammond,-87.494981,2021,0.04,Pb,41.674278
59,181270027.0,Burns Harbor - Port of Indiana,Porter,Burns Harbor - Port of Indiana,-87.150367,2021,0.01,Pb,41.635181
...,...,...,...,...,...,...,...,...,...
2467,181730008.0,Boonville,Warrick,Boonville,-87.278333,2024**,0.067,O3,38.051944
2468,181730009.0,Lynnville,Warrick,Lynnville,-87.341396,2024**,NaN,O3,38.194501
2469,181730011.0,Dayville,Warrick,Dayville,-87.321933,2024**,0.065,O3,37.954450
2470,170230001.0,West Union,Clark,NaN,-87.668297,2024**,0.063,O3,39.210857
2471,260270003.0,Cassopolis,Cass,Cassopolis,-86.001629,2024**,0.066,O3,41.895570

In [219]:
combinedData.to_excel('/Users/yaminiane/Documents/Hackathon/Air Quality/Transformed Data/Data.xlsx', index=False)